[2025-02-26T20:43:26.455+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T20:43:26.471+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T20:43:26.483+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T20:43:26.484+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:43:26.504+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-25 00:00:00+00:00
[2025-02-26T20:43:26.516+0000] {standard_task_runner.py:57} INFO - Started process 180 to run task
[2025-02-26T20:43:26.521+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmpqhc7olz5']
[2025-02-26T20:43:26.527+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask store_raw_data_in_hdfs
[2025-02-26T20:43:26.558+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T20:43:26.618+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [running]> on host c245dae1ddc2
[2025-02-26T20:43:26.634+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T20:43:26.698+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T20:43:26.720+0000] {logging_mixin.py:151} INFO - /tmp
[2025-02-26T20:43:28.841+0000] {logging_mixin.py:151} INFO - Données stockées dans HDFS : /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25/coingecko_raw.json
[2025-02-26T20:43:28.843+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:43:28.861+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=coingecko_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250225T000000, start_date=20250226T204326, end_date=20250226T204328
[2025-02-26T20:43:28.919+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:43:28.959+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:58:06.788+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T20:58:06.803+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T20:58:06.814+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T20:58:06.814+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:58:06.831+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-25 00:00:00+00:00
[2025-02-26T20:58:06.836+0000] {standard_task_runner.py:57} INFO - Started process 174 to run task
[2025-02-26T20:58:06.840+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmpbxghgqvw']
[2025-02-26T20:58:06.844+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask store_raw_data_in_hdfs
[2025-02-26T20:58:06.862+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T20:58:06.903+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [running]> on host 689609bdff45
[2025-02-26T20:58:06.917+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T20:58:07.001+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T20:58:07.030+0000] {logging_mixin.py:151} INFO - /tmp
[2025-02-26T20:58:08.978+0000] {logging_mixin.py:151} INFO - Erreur lors de l'exécution de la commande Docker/HDFS: Command '['docker cp /tmp/coingecko_raw.json namenode:/tmp/coingecko_raw.json']' returned non-zero exit status 1.
[2025-02-26T20:58:08.980+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coingecko_pipeline.py", line 66, in store_raw_data_in_hdfs
    subprocess.run(["docker cp /tmp/coingecko_raw.json namenode:/tmp/coingecko_raw.json"],shell=True,check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker cp /tmp/coingecko_raw.json namenode:/tmp/coingecko_raw.json']' returned non-zero exit status 1.
[2025-02-26T20:58:08.993+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=coingecko_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250225T000000, start_date=20250226T205806, end_date=20250226T205808
[2025-02-26T20:58:09.009+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task store_raw_data_in_hdfs (Command '['docker cp /tmp/coingecko_raw.json namenode:/tmp/coingecko_raw.json']' returned non-zero exit status 1.; 174)
[2025-02-26T20:58:09.029+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T20:58:09.045+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T21:28:18.768+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T21:28:18.781+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T21:28:18.790+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T21:28:18.791+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T21:28:18.804+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-25 00:00:00+00:00
[2025-02-26T21:28:18.809+0000] {standard_task_runner.py:57} INFO - Started process 180 to run task
[2025-02-26T21:28:18.814+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmpwzz4gkb9']
[2025-02-26T21:28:18.821+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask store_raw_data_in_hdfs
[2025-02-26T21:28:18.858+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T21:28:18.927+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [running]> on host a932aabdd774
[2025-02-26T21:28:18.939+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T21:28:19.011+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T21:28:19.038+0000] {logging_mixin.py:151} INFO - /tmp
[2025-02-26T21:28:19.039+0000] {logging_mixin.py:151} INFO - file created 
[2025-02-26T21:28:21.366+0000] {logging_mixin.py:151} INFO - dir created
[2025-02-26T21:28:21.409+0000] {logging_mixin.py:151} INFO - Données stockées dans HDFS : /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25/coingecko_raw.json
[2025-02-26T21:28:21.413+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T21:28:21.452+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=coingecko_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250225T000000, start_date=20250226T212818, end_date=20250226T212821
[2025-02-26T21:28:21.575+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T21:28:21.603+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T21:40:10.203+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T21:40:10.227+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T21:40:10.247+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T21:40:10.249+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T21:40:10.275+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-25 00:00:00+00:00
[2025-02-26T21:40:10.282+0000] {standard_task_runner.py:57} INFO - Started process 210 to run task
[2025-02-26T21:40:10.289+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmpj511xpan']
[2025-02-26T21:40:10.295+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask store_raw_data_in_hdfs
[2025-02-26T21:40:10.324+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T21:40:10.395+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [running]> on host 2dc9d2d4b647
[2025-02-26T21:40:10.414+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T21:40:10.503+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T21:40:10.532+0000] {logging_mixin.py:151} INFO - /tmp
[2025-02-26T21:40:10.542+0000] {logging_mixin.py:151} INFO - file created 
[2025-02-26T21:40:12.771+0000] {logging_mixin.py:151} INFO - dir created
[2025-02-26T21:40:12.780+0000] {logging_mixin.py:151} INFO - feedback : 
[2025-02-26T21:40:12.781+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T21:40:12.793+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=coingecko_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250225T000000, start_date=20250226T214010, end_date=20250226T214012
[2025-02-26T21:40:12.855+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T21:40:12.870+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T22:00:58.473+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T22:00:58.491+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T22:00:58.508+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T22:00:58.509+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T22:00:58.537+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-25 00:00:00+00:00
[2025-02-26T22:00:58.545+0000] {standard_task_runner.py:57} INFO - Started process 260 to run task
[2025-02-26T22:00:58.551+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmpnnux3qr5']
[2025-02-26T22:00:58.559+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask store_raw_data_in_hdfs
[2025-02-26T22:00:58.585+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T22:00:58.652+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [running]> on host c29a8e62ca6c
[2025-02-26T22:00:58.670+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T22:00:58.796+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T22:00:58.856+0000] {logging_mixin.py:151} INFO - result of | cd ../../../tmp && ls | :
[2025-02-26T22:00:58.859+0000] {logging_mixin.py:151} INFO -  2029240f6d1128be89ddc32729463129
hh.json
pymp-88fhiygm
pymp-fqk8c7u4
tmp7gcz89_m
xx.json
[2025-02-26T22:00:58.889+0000] {logging_mixin.py:151} INFO - result of | cd ../ && ls | :
[2025-02-26T22:00:58.891+0000] {logging_mixin.py:151} INFO -  ***
microsoft
[2025-02-26T22:00:58.914+0000] {logging_mixin.py:151} INFO - result of | cd ../../../ && ls | :
[2025-02-26T22:00:58.916+0000] {logging_mixin.py:151} INFO -  ***-scheduler-autorestart
bin
boot
clean-logs
dev
entrypoint
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
scripts
srv
sys
tmp
usr
var
[2025-02-26T22:00:58.918+0000] {logging_mixin.py:151} INFO - ***-scheduler-autorestart
bin
boot
clean-logs
dev
entrypoint
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
scripts
srv
sys
tmp
usr
var
[2025-02-26T22:00:58.944+0000] {logging_mixin.py:151} INFO - file created 
[2025-02-26T22:01:01.934+0000] {logging_mixin.py:151} INFO - dir created
[2025-02-26T22:01:01.961+0000] {logging_mixin.py:151} INFO - feedback : 
[2025-02-26T22:01:01.963+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T22:01:01.988+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=coingecko_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250225T000000, start_date=20250226T220058, end_date=20250226T220101
[2025-02-26T22:01:02.055+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T22:01:02.091+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T22:21:10.703+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T22:21:10.715+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T22:21:10.726+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T22:21:10.727+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T22:21:10.742+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-25 00:00:00+00:00
[2025-02-26T22:21:10.747+0000] {standard_task_runner.py:57} INFO - Started process 200 to run task
[2025-02-26T22:21:10.750+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmp84oognsn']
[2025-02-26T22:21:10.753+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask store_raw_data_in_hdfs
[2025-02-26T22:21:10.771+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T22:21:10.808+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [running]> on host 255190ede082
[2025-02-26T22:21:10.821+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T22:21:10.889+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T22:21:10.919+0000] {logging_mixin.py:151} INFO - result of | cd ../../../tmp && ls | :
[2025-02-26T22:21:10.920+0000] {logging_mixin.py:151} INFO -  2029240f6d1128be89ddc32729463129
hh.json
pymp-fqk8c7u4
pymp-lk42pa91
tmp7gcz89_m
xx.json
[2025-02-26T22:21:10.942+0000] {logging_mixin.py:151} INFO - result of | cd ../ && ls | :
[2025-02-26T22:21:10.943+0000] {logging_mixin.py:151} INFO -  ***
microsoft
[2025-02-26T22:21:10.957+0000] {logging_mixin.py:151} INFO - result of | cd ../../../ && ls | :
[2025-02-26T22:21:10.958+0000] {logging_mixin.py:151} INFO -  ***-scheduler-autorestart
bin
boot
clean-logs
dev
entrypoint
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
scripts
srv
sys
tmp
usr
var
[2025-02-26T22:21:10.959+0000] {logging_mixin.py:151} INFO - ***-scheduler-autorestart
bin
boot
clean-logs
dev
entrypoint
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
scripts
srv
sys
tmp
usr
var
[2025-02-26T22:21:10.971+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coingecko_pipeline.py", line 59, in store_raw_data_in_hdfs
    with open(local_file, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cd ../../../tmp/coingecko_raw.json'
[2025-02-26T22:21:10.982+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=coingecko_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250225T000000, start_date=20250226T222110, end_date=20250226T222110
[2025-02-26T22:21:10.997+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task store_raw_data_in_hdfs ([Errno 2] No such file or directory: 'cd ../../../tmp/coingecko_raw.json'; 200)
[2025-02-26T22:21:11.010+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T22:21:11.029+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T22:43:29.532+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T22:43:29.548+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T22:43:29.559+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T22:43:29.560+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T22:43:29.578+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-25 00:00:00+00:00
[2025-02-26T22:43:29.584+0000] {standard_task_runner.py:57} INFO - Started process 184 to run task
[2025-02-26T22:43:29.589+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmpu4xi_j6_']
[2025-02-26T22:43:29.594+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask store_raw_data_in_hdfs
[2025-02-26T22:43:29.619+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T22:43:29.658+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-25T00:00:00+00:00 [running]> on host 2c0e598ffd0f
[2025-02-26T22:43:29.672+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-26T22:43:29.761+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T22:43:29.810+0000] {logging_mixin.py:151} INFO - result of | cd ../../../tmp && ls | :
[2025-02-26T22:43:29.811+0000] {logging_mixin.py:151} INFO -  2029240f6d1128be89ddc32729463129
coingecko_raw.json
hh.json
pymp-fqk8c7u4
pymp-kmbpuwje
tmp7gcz89_m
xx.json
[2025-02-26T22:43:29.836+0000] {logging_mixin.py:151} INFO - result of | cd ../ && ls | :
[2025-02-26T22:43:29.837+0000] {logging_mixin.py:151} INFO -  ***
microsoft
[2025-02-26T22:43:29.857+0000] {logging_mixin.py:151} INFO - result of | cd ../../../ && ls | :
[2025-02-26T22:43:29.858+0000] {logging_mixin.py:151} INFO -  ***-scheduler-autorestart
bin
boot
clean-logs
dev
entrypoint
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
scripts
srv
sys
tmp
usr
var
[2025-02-26T22:43:29.859+0000] {logging_mixin.py:151} INFO - ***-scheduler-autorestart
bin
boot
clean-logs
dev
entrypoint
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
scripts
srv
sys
tmp
usr
var
[2025-02-26T22:43:29.896+0000] {logging_mixin.py:151} INFO - result of | cd ../../../tmp && ls | :
[2025-02-26T22:43:29.897+0000] {logging_mixin.py:151} INFO -  2029240f6d1128be89ddc32729463129
coingecko_raw.json
hh.json
pymp-fqk8c7u4
pymp-kmbpuwje
tmp7gcz89_m
xx.json
[2025-02-26T22:43:29.897+0000] {logging_mixin.py:151} INFO - file created 
[2025-02-26T22:43:33.076+0000] {logging_mixin.py:151} INFO - dir created
[2025-02-26T22:43:35.075+0000] {logging_mixin.py:151} INFO - Erreur lors de l'exécution de la commande Docker/HDFS: Command '['docker  exec -u root namenode hdfs dfs -put -f ../../../tmp/coingecko_raw.json /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25']' returned non-zero exit status 1.
[2025-02-26T22:43:35.079+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/coingecko_pipeline.py", line 79, in store_raw_data_in_hdfs
    subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker  exec -u root namenode hdfs dfs -put -f ../../../tmp/coingecko_raw.json /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25']' returned non-zero exit status 1.
[2025-02-26T22:43:35.108+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=coingecko_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250225T000000, start_date=20250226T224329, end_date=20250226T224335
[2025-02-26T22:43:35.138+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task store_raw_data_in_hdfs (Command '['docker  exec -u root namenode hdfs dfs -put -f ../../../tmp/coingecko_raw.json /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25']' returned non-zero exit status 1.; 184)
[2025-02-26T22:43:35.161+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T22:43:35.185+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
