[2025-02-28T00:23:16.081+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T00:23:16.089+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: coingecko_ingestion_dag.fetch_data scheduled__2025-02-27T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-02-28T00:23:16.104+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
