[2025-02-28T10:02:34.131+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T10:02:34.144+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-27T00:00:00+00:00 [queued]>
[2025-02-28T10:02:34.155+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-27T00:00:00+00:00 [queued]>
[2025-02-28T10:02:34.155+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-28T10:02:34.172+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-27 00:00:00+00:00
[2025-02-28T10:02:34.180+0000] {standard_task_runner.py:57} INFO - Started process 269 to run task
[2025-02-28T10:02:34.186+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_ingestion_dag', 'run_mapreduce_job', 'scheduled__2025-02-27T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/coingecko_pipeline.py', '--cfg-path', '/tmp/tmpl5ljwy_s']
[2025-02-28T10:02:34.190+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask run_mapreduce_job
[2025-02-28T10:02:34.222+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T10:02:34.284+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_ingestion_dag.run_mapreduce_job scheduled__2025-02-27T00:00:00+00:00 [running]> on host 4b23b52130d5
[2025-02-28T10:02:34.297+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T10:02:34.390+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-27T00:00:00+00:00'
[2025-02-28T10:02:34.392+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-28T10:02:34.393+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec -i namenode bash -c "\n        hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar    -files /tmp/mapper.py,/tmp/reducer.py    -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/coingecko_raw.json    -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26    -mapper mapper.py    -reducer reducer.py"\n        ']
[2025-02-28T10:02:34.404+0000] {subprocess.py:86} INFO - Output:
[2025-02-28T10:02:37.095+0000] {subprocess.py:93} INFO - 2025-02-28 10:02:37,094 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-28T10:02:37.171+0000] {subprocess.py:93} INFO - 2025-02-28 10:02:37,170 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-28T10:02:37.171+0000] {subprocess.py:93} INFO - 2025-02-28 10:02:37,170 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-28T10:02:37.194+0000] {subprocess.py:93} INFO - 2025-02-28 10:02:37,193 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-28T10:02:37.562+0000] {subprocess.py:93} INFO - 2025-02-28 10:02:37,561 INFO mapreduce.JobSubmitter: Cleaning up the staging area file:/tmp/hadoop/mapred/staging/root114103849/.staging/job_local114103849_0001
[2025-02-28T10:02:37.564+0000] {subprocess.py:93} INFO - 2025-02-28 10:02:37,563 ERROR streaming.StreamJob: Error Launching job : Input path does not exist: hdfs://namenode:9000/user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/coingecko_raw.json
[2025-02-28T10:02:37.565+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-28T10:02:38.114+0000] {subprocess.py:97} INFO - Command exited with return code 5
[2025-02-28T10:02:38.143+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2025-02-28T10:02:38.152+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=coingecko_ingestion_dag, task_id=run_mapreduce_job, execution_date=20250227T000000, start_date=20250228T100234, end_date=20250228T100238
[2025-02-28T10:02:38.180+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 5.; 269)
[2025-02-28T10:02:38.219+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-28T10:02:38.255+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
